#!/bin/sh
#
if [ $# -eq 0 ]; then
    echo "usage: mkvenv <env_name> [<package> <package> ...]"
	exit 0
fi

venvname=$1

if [ -z "$VENVDIR" ]; then
	export VENVDIR=~/".local/virtualenvs"
fi

if [ -e "$VENVDIR" ]; then
	echo "Directory of venvs: $VENVDIR"
else
	echo "Directory doesn't exist, would like to make it in $VENVDIR?"
	read -n 1 -p "(y/N) " answer

	if [[ $answer == "Y" || $answer == "y" ]]; then
		mkdir $VENVDIR
		echo "Directory created."
	else
		echo "If you want to make directory on another path, set VENVDIR variable."
		exit -1
	fi
fi

if [ -e "$VENVDIR" ]; then
	if [ -e "$VENVDIR/$venvname" ]; then
		echo "venv already exitsts"
		exit -1
	fi
	echo "creating venv"
	cd $VENVDIR
	python -m venv $venvname


	shift
	# Iterate through the remaining arguments
	for arg in "$@"; do
		cd $venvname
		bin/python -m pip install $arg
	done
fi
